### ISSUE TITLE
Ruby Capstone Project Kanban setup

### ISSUE THREAD

**Issue by mnaibei** [emhamza/Catalog-of-my-things#19]
- Kanban board link: https://github.com/emhamza/Catalog-of-my-things/projects/1
- There are 3 people on our team
- Team member 1 Mercy Mugambi
- Team member 2 Mucha Naibei
- Team member 3 Umair Hamza

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @mnaibei, @mercymugambi and @emhamza,

✔️ Tasks are complete and properly assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
